name = "AdversialEstimation"
uuid = "5113b226-6701-428a-9571-47c44db53423"
authors = ["Santeri V채채t채j채"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
